In [1]:
import pandas as pd

Reading the sheets for different Years(2009-2010,2010-2011) from the excel file

In [2]:
df_2009 = pd.read_csv(r"C:\Users\Lenovo\Downloads\online_retail_II_raw-Year 2009-2010,online_retail_II_raw-Year 2010-2011\online_retail_II_raw-Year 2009-2010.csv")

In [3]:
df_2009

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,12/9/2010 20:01,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,12/9/2010 20:01,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,12/9/2010 20:01,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,12/9/2010 20:01,1.95,17530.0,United Kingdom

In [4]:
df_2010 = pd.read_csv(r"C:\Users\Lenovo\Downloads\online_retail_II_raw-Year 2009-2010,online_retail_II_raw-Year 2010-2011\online_retail_II_raw-Year 2010-2011.csv")

displaying first 5 rows

In [5]:
display(df_2009.head(10))

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,12/1/2009 7:45,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,12/1/2009 7:45,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,12/1/2009 7:46,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,12/1/2009 7:46,3.75,13085.0,United Kingdom

displaying last 5 rows

In [6]:
display(df_2010.tail())

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France
541909,581587,POST,POSTAGE,1,12/9/2011 12:50,18.00,12680.0,France

combining the two dataframes into a single dataframe . ignore_index removes the old index .df.shape gives the count of rows and columns

In [7]:
df=pd.concat([df_2009,df_2010],ignore_index=True)
print(df.shape)

(1067371, 8)

In [8]:
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,12/9/2011 12:50,18.00,12680.0,France

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

This step is used to identify missing values in each column of the dataset.

In [10]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

This command counts the number of duplicate rows in the dataset.

In [11]:
print(df.duplicated().sum())

34335

Revenue is calculated by multiplying the Quantity of items purchased with their Price.
This step is essential for analyzing sales performance, as it provides the monetary value of each transaction.

In [12]:
df["Revenue"]=df["Quantity"]*df["Price"]

In [13]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,12/1/2009 7:45,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,12/1/2009 7:45,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,12/1/2009 7:45,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,12/1/2009 7:45,1.25,13085.0,United Kingdom,30.0

Converts the InvoiceDate column from string format into a proper DateTime object.
This allows for powerful time‑based operations such as:
-Extracting year, month, day, or hour.
-Grouping transactions by month or quarter.
-Performing time series analysis (e.g., sales trends over time).
-Filtering data by specific date ranges

In [14]:
df["InvoiceDate"]=pd.to_datetime(df["InvoiceDate"])

After converting InvoiceDate into a proper DateTime object, this step extracts the year component.
Creates a new column Year that stores the year of each transaction.

In [15]:
df["Year"]=df["InvoiceDate"].dt.year

After converting InvoiceDate into a proper DateTime object, this step extracts the month name (e.g., January, February).
Creates a new column Month that stores the month of each transaction.
Useful for:
-Seasonal trend analysis

In [16]:
df["Month"]=df["InvoiceDate"].dt.month_name()

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 11 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
 8   Revenue      1067371 non-null  float64
 9   Year         1067371 non-null  int32
 10  Month        1067371 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(5)
memory usage: 85.5+ MB

Filters the dataset to show all duplicate rows based on a subset of columns:
Invoice,InvoiceDate,Customer ID

Using keep=False ensures all copies of duplicates are returned, not just one.This helps detect:
-Transactions logged multiple times.
-Data entry errors.
-Potential issues in merging or importing datasets.

In retail datasets, it’s common for one invoice to contain multiple products.
In that case, Invoice, InvoiceDate, and Customer ID may be the same, but Description differs.
These are valid multi‑line invoices, not errors.
True duplicates are rows where all fields match (including product, quantity, and price).

In [18]:
df_duplicated=df[df.duplicated(subset=["Invoice","InvoiceDate","Customer ID"],keep=False)]

In [19]:
df_duplicated

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.40,2009,December
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00,2009,December
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00,2009,December
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.80,2009,December
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.00,2009,December
...,...,...,...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011,December
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011,December
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011,December
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011,December
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00,2011,December

duplicated() checks for rows that are repeated across the dataset.By default, it considers all columns when determining duplicates.
The parameter keep=False ensures that every occurrence of a duplicate row is marked as duplicate, not just the later one
Useful for:
-Spotting repeated transactions.
-Auditing data quality.
-Deciding whether to remove duplicates with df.drop_duplicates()

In [20]:
df[df.duplicated(keep=False)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,3.75,2009,December
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,3.75,2009,December
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom,3.75,2009,December
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom,7.80,2009,December
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom,5.10,2009,December
...,...,...,...,...,...,...,...,...,...,...,...
1067136,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom,0.39,2011,December
1067150,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom,2.49,2011,December
1067153,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom,1.95,2011,December
1067160,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom,2.10,2011,December
1067162,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom,2.08,2011,December

df["Customer ID"].isnull().sum() → Counts how many rows have a missing Customer ID.
len(df) → Gives the total number of rows in the dataset.
Dividing the two and multiplying by 100 → Calculates the percentage of missing Customer IDs.

In [21]:
(df["Customer ID"].isnull().sum())/len(df)*100

np.float64(22.766872999172733)

22.7% of rows have missing Customer ID.
Because nearly one‑quarter of the dataset lacks customer identifiers, we adopt a dual‑track analysis:

Customer-Level Track
Drop rows with missing IDs to ensure accurate customer insights.Use this cleaned dataset for segmentation, retention, and lifetime value analysis.

Invoice-Level Track
Keep all rows, including those with missing IDs.
Use this dataset for revenue trends, product mix, AOV, and highest value orders.

Optionally tag missing IDs as "Unknown" to preserve all transactions while distinguishing them.

Business Insight
This dual approach ensures we don’t lose ~23% of revenue data, while still maintaining accuracy for customer‑focused KPIs.

Track 1: Customer‑Level Dataset
Created by dropping rows with missing Customer ID:

In [22]:
df_customer = df.dropna(subset=["Customer ID"])

df_customer is datset with no missing Customer IDs

In [23]:
df_customer

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.40,2009,December
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00,2009,December
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.00,2009,December
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.80,2009,December
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.00,2009,December
...,...,...,...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011,December
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011,December
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011,December
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011,December
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France,18.00,2011,December

In [24]:
df_customer.shape[0]

824364

count of Transactions without customer id

In [25]:
df.shape[0]-df_customer.shape[0]

243007

Actual customer base size=Unique Customers

This will return the number of unique customer IDs in your dataset df_customer

In [ ]:
df_customer["Customer ID"].nunique()

We are not dropping duplicates immediately — they represent multiple transactions per customer.
Instead, aggregate later when we want customer‑level insights. This way we preserve transaction history

In [ ]:
 df_customer[df_customer["Quantity"] < 0].count() #represents negative quantities(no sales or cancelled orders)

In [ ]:
Presence of negative quantities tells that dataset includes product returns or adjustments.

We will create a separate sales dataframe

In [ ]:
sales_df=df[df["Quantity"]>0].copy()

In [ ]:
sales_df.head()

AOV should be calculated using sales_df, which includes only completed sales and excludes cancelled or returned orders. This ensures the metric accurately reflects average sales performance without being reduced by negative transactions. Since AOV is a sales KPI, it should be calculated for all completed orders, regardless of whether CustomerID is available.
Average Order Value (AOV): The average revenue generated from each completed order, calculated by averaging the total revenue of all completed invoices.

In [ ]:
Average_Order_Value=sales_df.groupby("Invoice")["Revenue"].sum().mean().round(2)

In [ ]:
Average_Order_Value

Check for missing country values

In [ ]:
sales_df["Country"].isnull().sum()

Check for blank country names

In [ ]:
(sales_df["Country"].str.strip() == "").sum()

Count unique countries

In [ ]:
sales_df["Country"].nunique()

Check revenue distribution by country

In [ ]:
revenue_by_country=sales_df.groupby("Country")["Revenue"].sum().sort_values(ascending=False).round(2)
print(revenue_by_country.head())

Created a separate DataFrame containing only return/cancellation transactions.
To ensure you're capturing only genuine returns, you can combine both conditions that the row is selected only if both conditions are true:
Quantity is negative AND
Invoice starts with "C"

In [ ]:
returns_df = df[
    (df["Quantity"] < 0) &
    (df["Invoice"].astype(str).str.startswith("C"))
].copy()

In [ ]:
returns_df.head()

In [ ]:
returns_df.shape

In [ ]:
returns_df.isnull().sum()

In [ ]:
returns_df.describe()

Total Returned Revenue
This indicates the total financial impact of returns

In [ ]:
total_returned_revenue=abs(returns_df["Revenue"].sum())
print(total_returned_revenue)

Total Return Transactions

In [ ]:
total_return_transactions=returns_df["Invoice"].nunique()
print(total_return_transactions)

check whether description is missing

In [ ]:
returns_df["Description"].isnull().sum()

Most Returned Products

In [ ]:
most_returned_products=returns_df.groupby("Description")["Quantity"].sum().abs().sort_values(ascending=False).head(10)

In [ ]:
most_returned_products

A few products exhibit unusually high return quantities, suggesting bulk cancellations or inventory adjustments. These values may not represent typical customer return behavior

Converting to csv file as cleaned dataset

In [ ]:
sales_df.to_csv("cleaned_onlinesales.csv", index=False)